// Generated by gencpp from file ros_robot_localization/CalculateTransformationMatrix.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_LOCALIZATION_MESSAGE_CALCULATETRANSFORMATIONMATRIX_H
#define ROS_ROBOT_LOCALIZATION_MESSAGE_CALCULATETRANSFORMATIONMATRIX_H

#include <ros/service_traits.h>


#include <ros_robot_localization/CalculateTransformationMatrixRequest.h>
#include <ros_robot_localization/CalculateTransformationMatrixResponse.h>


namespace ros_robot_localization
{

struct CalculateTransformationMatrix
{

typedef CalculateTransformationMatrixRequest Request;
typedef CalculateTransformationMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculateTransformationMatrix
} // namespace ros_robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_robot_localization::CalculateTransformationMatrix > {
  static const char* value()
  {
    return "0cca352eb50cd0fb14f365adcdd04d60";
  }

  static const char* value(const ::ros_robot_localization::CalculateTransformationMatrix&) { return value(); }
};

template<>
struct DataType< ::ros_robot_localization::CalculateTransformationMatrix > {
  static const char* value()
  {
    return "ros_robot_localization/CalculateTransformationMatrix";
  }

  static const char* value(const ::ros_robot_localization::CalculateTransformationMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::ros_robot_localization::CalculateTransformationMatrixRequest> should match
// service_traits::MD5Sum< ::ros_robot_localization::CalculateTransformationMatrix >
template<>
struct MD5Sum< ::ros_robot_localization::CalculateTransformationMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_localization::CalculateTransformationMatrix >::value();
  }
  static const char* value(const ::ros_robot_localization::CalculateTransformationMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_localization::CalculateTransformationMatrixRequest> should match
// service_traits::DataType< ::ros_robot_localization::CalculateTransformationMatrix >
template<>
struct DataType< ::ros_robot_localization::CalculateTransformationMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::ros_robot_localization::CalculateTransformationMatrix >::value();
  }
  static const char* value(const ::ros_robot_localization::CalculateTransformationMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_robot_localization::CalculateTransformationMatrixResponse> should match
// service_traits::MD5Sum< ::ros_robot_localization::CalculateTransformationMatrix >
template<>
struct MD5Sum< ::ros_robot_localization::CalculateTransformationMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_robot_localization::CalculateTransformationMatrix >::value();
  }
  static const char* value(const ::ros_robot_localization::CalculateTransformationMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_robot_localization::CalculateTransformationMatrixResponse> should match
// service_traits::DataType< ::ros_robot_localization::CalculateTransformationMatrix >
template<>
struct DataType< ::ros_robot_localization::CalculateTransformationMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::ros_robot_localization::CalculateTransformationMatrix >::value();
  }
  static const char* value(const ::ros_robot_localization::CalculateTransformationMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ROBOT_LOCALIZATION_MESSAGE_CALCULATETRANSFORMATIONMATRIX_H
